# File .chipperci.yml, which goes in the root of your repository
version: 5


environment:
  php: 8.1    # 7.1, 7.2, 7.3, 7.4, 8.0, 8.1, 8.2
  node: 18    # 6, 8, 10, 12, 14, 16, 18

#services:
#  - mysql: 5.7

pipeline:
  - name: Install Aws
    cmd: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      sudo apt-get update && sudo apt-get install -yy less

  - name: Setup
    cmd: |
    
      aws --version
      aws configure set aws_access_key_id $AWS_CLIENT_ID_NEW
      aws configure set aws_secret_access_key $AWS_SECRET_ID_NEW
      aws configure set region eu-central-1
      composer install --no-interaction --prefer-dist --optimize-autoloader
      aws s3 ls
      aws s3 sync ./vendor s3://chipperci/deployed --recursive
      aws s3 sync ./composer.json s3://chipperci/deployed 
      aws s3 sync ./composer.lock s3://chipperci/deployed 
      aws s3 sync ./index.html s3://chipperci/deployed 
      aws s3 sync ./public s3://chipperci/deployed --recursive
      aws datasync start-task-execution --task-arn arn:aws:datasync:eu-central-1:683422126298:task/task-0903ba47c9cc57521
      
  - name: Check files
    cmd: ls -la
