# File .chipperci.yml, which goes in the root of your repository
version: 1

environment:
  php: 8.2    # 7.1, 7.2, 7.3, 7.4, 8.0, 8.1, 8.2
  node: 18    # 6, 8, 10, 12, 14, 16, 18

#services:
#  - mysql: 5.7

pipeline:
  - name: Install Aws
    cmd: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install

  - name: Setup
    cmd: |
      aws --version
      aws configure set aws_access_key_id mytest
      aws configure set aws_secret_access_key
      aws sts get-caller-identity
      composer install --no-interaction --prefer-dist --optimize-autoloader
      
  - name: Check files
    cmd: ls -la
