# File .chipperci.yml, which goes in the root of your repository
version: 5


environment:
  php: 8.1    # 7.1, 7.2, 7.3, 7.4, 8.0, 8.1, 8.2
  node: 18    # 6, 8, 10, 12, 14, 16, 18

#services:
#  - mysql: 5.7

pipeline:
  - name: Init
    cmd: |
      echo ${CI_COMMIT_SHA}
      echo ${CI_COMMIT_SHA_SHORT}
      echo "testing"
  - name: Install Aws
    cmd: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      sudo apt-get update && sudo apt-get install -yy less
  - name: Setup
    cmd: |
      composer install --no-interaction --prefer-dist --optimize-autoloader
  - name: Move Files
    cmd: | 
      aws --version
      aws configure set aws_access_key_id $AWS_CLIENT_ID_NEW
      aws configure set aws_secret_access_key $AWS_SECRET_ID_NEW
      aws configure set region eu-central-1
      aws s3 cp . s3://chipperci --recursive --exclude 'aws/*' --exclude '.git/*' --exclude 'awscliv2.zip'
      aws datasync start-task-execution --task-arn arn:aws:datasync:eu-central-1:683422126298:task/task-0903ba47c9cc57521
      #aws codebuild start-build  --project-name my-db-deploy --artifacts-override="{\"type\": \"S3\", \"location\": \"arn:aws:s3:::codepipeline-us-east-1-4444442770/my-db-dev-deploy/BuildArtif/ZepddNIiV\",\"encryptionDisabled\": false}" --environment-variables-override name='environment',value='prod'--environment-variables-override name='delete_on_termination_db_ebs_volume',value='true'
    
